### ISSUE TITLE
LoadError running rake assets:precompile:primary

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/ofn_deployment#21]
This is to build a vagrant box, happens in development, test and staging environments:

```
LoadError: cannot load such file -- open_food_network/searcher
/home/vagrant/.gem/ruby/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/vagrant/.gem/ruby/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/vagrant/.gem/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `block in require'
/home/vagrant/.gem/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/vagrant/.gem/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/home/vagrant/apps/openfoodnetwork/current/config/initializers/spree.rb:11:in `<top (required)>'
/home/vagrant/.gem/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/home/vagrant/.gem/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `block in load'
/home/vagrant/.gem/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/vagrant/.gem/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/home/vagrant/.gem/ruby/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
/home/vagrant/.gem/ruby/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:592:in `each'
/home/vagrant/.gem/ruby/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:592:in `block in <class:Engine>'
/home/vagrant/.gem/ruby/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
/home/vagrant/.gem/ruby/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `run'
/home/vagrant/.gem/ruby/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/vagrant/.gem/ruby/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `each'
/home/vagrant/.gem/ruby/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `run_initializers'
/home/vagrant/.gem/ruby/1.9.1/gems/railties-3.2.19/lib/rails/application.rb:136:in `initialize!'
/home/vagrant/.gem/ruby/1.9.1/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/vagrant/apps/openfoodnetwork/current/config/environment.rb:5:in `<top (required)>'
/home/vagrant/.gem/ruby/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/vagrant/.gem/ruby/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/vagrant/.gem/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `block in require'
/home/vagrant/.gem/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/vagrant/.gem/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/home/vagrant/.gem/ruby/1.9.1/gems/railties-3.2.19/lib/rails/application.rb:103:in `require_environment!'
/home/vagrant/.gem/ruby/1.9.1/gems/railties-3.2.19/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/home/vagrant/.gem/ruby/1.9.1/gems/turbo-sprockets-rails3-0.3.6/lib/turbo-sprockets/tasks/assets.rake:184:in `block (2 levels) in <top (required)>'
```

**Comment by pmackay** [comment]
Closing as as separate spree.rb file no longer needed
